[package]
name = "pdbtbx"
version = "0.6.3"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
license = "MIT"
edition = "2018"
description = "A library to open/edit/save (crystallographic) Protein Data Bank (PDB) and mmCIF files."
repository = "https://github.com/nonnominandus/pdbtbx"
readme = "README.md"
keywords = ["pdb", "crystal", "protein", "mmcif", "bio"]
categories = ["parser-implementations", "science"]
include = ["src/**/*", "LICENSE", "README.md"]

[dependencies]
rstar = { version = "0.8.3", optional = true}
serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"

[package.metadata.docs.rs]
all-features = true

[profile.dev]
opt-level = 3

[[bench]]
name = "benchmark"
harness = false
path = "benches/benchmark.rs"
